id: QmU8VCp2Yh7vs2KBRfjfzFoxY1dqcqKG2kAfdJagYBHun4
description: Returns a socket url to the matched channel
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /ws/url
domains:
    - testDomain
includes:
    - /functions/getsocketurl.go
execution:
    timeout: 10s
    memory: 10MB
    call: getsocketurl
